# Generated by Django 6.0.4 on 2026-04-08 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CelestialBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('gravity', models.FloatField()),
                ('mass', models.FloatField()),
                ('radius', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galaxy', models.CharField(max_length=100)),
                ('solar_system', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_temperature', models.FloatField()),
                ('atmospheric_composition', models.TextField()),
                ('weather_conditions', models.TextField()),
                ('surface_pressure', models.FloatField()),
                ('magnetic_field_strength', models.FloatField()),
                ('celestial_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodies.celestialbody')),
            ],
        ),
        migrations.CreateModel(
            name='Limitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exploration_difficulty', models.CharField(max_length=100)),
                ('human_survivability', models.CharField(max_length=100)),
                ('surface_mobility', models.CharField(max_length=100)),
                ('fuel_contraints', models.FloatField()),
                ('data_communication_delay', models.FloatField()),
                ('distance_from_earth', models.FloatField()),
                ('power_requirements', models.FloatField()),
                ('distance_from_sun', models.FloatField()),
                ('radiation_protection', models.CharField(max_length=100)),
                ('radiation_levels', models.FloatField()),
                ('celestial_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodies.celestialbody')),
                ('enviorment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodies.environment')),
            ],
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodies.region'),
        ),
    ]
