# Generated by Django 6.0.4 on 2026-04-28 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_guess_unique_together_dailyplaycount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyplaycount',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='guess',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dailyplaycount',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date'),
        ),
        migrations.AddConstraint(
            model_name='guess',
            constraint=models.UniqueConstraint(fields=('game', 'attempt_number'), name='unique_game_attempt'),
        ),
    ]
