# Generated by Django 6.0.4 on 2026-04-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_dailyplaycount_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplaycount',
            name='purchased',
            field=models.IntegerField(default=0),
        ),
    ]
