# Generated by Django 6.0.4 on 2026-04-30 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_add_purchased_to_daily_play_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlayBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plays_remaining', models.IntegerField(default=0)),
                ('last_reset', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='play_bank', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
