# Generated by Django 6.0.4 on 2026-04-30 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_add_user_play_bank'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyplaycount',
            name='unique_user_date',
        ),
        migrations.DeleteModel(
            name='DailyPlayCount',
        ),
    ]
